// ---- transactions_df teaching slice (8 rows) ----
const T_COLS=["order_id","customer_type","is_chain","province","product_category","channel","day_of_week","quantity","gross_revenue_thb","discount_thb"];
const TDATA=[
 {order_id:"ORD-0001",customer_type:"Casual Dining",is_chain:true,province:"Bangkok",product_category:"Vegetables",channel:"Mobile App",day_of_week:"Monday",quantity:12,gross_revenue_thb:3600,discount_thb:0},
 {order_id:"ORD-0002",customer_type:"Hotel",is_chain:true,province:"Phuket",product_category:"Seafood",channel:"Sales Rep",day_of_week:"Tuesday",quantity:20,gross_revenue_thb:12800,discount_thb:600},
 {order_id:"ORD-0003",customer_type:"Café & Bakery",is_chain:false,province:"Bangkok",product_category:"Eggs & Dairy",channel:"Web",day_of_week:"Wednesday",quantity:8,gross_revenue_thb:1900,discount_thb:0},
 {order_id:"ORD-0004",customer_type:"QSR",is_chain:true,province:"Chiang Mai",product_category:"Meat",channel:"Mobile App",day_of_week:"Thursday",quantity:30,gross_revenue_thb:9400,discount_thb:400},
 {order_id:"ORD-0005",customer_type:"Cloud Kitchen",is_chain:false,province:"Bangkok",product_category:"Vegetables",channel:"LINE",day_of_week:"Friday",quantity:15,gross_revenue_thb:4200,discount_thb:0},
 {order_id:"ORD-0006",customer_type:"Fine Dining",is_chain:false,province:"Phuket",product_category:"Seafood",channel:"Mobile App",day_of_week:"Friday",quantity:10,gross_revenue_thb:8800,discount_thb:500},
 {order_id:"ORD-0007",customer_type:"Catering",is_chain:true,province:"Songkhla",product_category:"Dry Goods",channel:"Sales Rep",day_of_week:"Saturday",quantity:40,gross_revenue_thb:7600,discount_thb:300},
 {order_id:"ORD-0008",customer_type:"Casual Dining",is_chain:false,province:"Chiang Mai",product_category:"Fruits",channel:"Web",day_of_week:"Sunday",quantity:18,gross_revenue_thb:3300,discount_thb:0}
];
TDATA.forEach((r,i)=>{r._i=i;});
// ---- verified aggregates from the FULL mkt_df (70 rows) and ops_df (201 rows) ----
const MKT_SPEND=[["Facebook",283468],["Google",193643],["LINE",151970],["Instagram",144681],["TikTok",119149],["Referral",46774],["Email",33429]];
const MKT_CAC=[["Referral",806],["Email",1337],["LINE",2303],["Google",3227],["Facebook",3831],["Instagram",4521],["TikTok",5180]];
const MKT_WEEKLY=[["2026-03-09",25],["2026-03-16",30],["2026-03-23",23],["2026-03-30",27],["2026-04-06",36],["2026-04-13",35],["2026-04-20",38],["2026-04-27",39],["2026-05-04",38],["2026-05-11",47]];
const OPS_DEPT=[["Warehouse & Fulfillment",70],["Logistics & Delivery",45],["Sourcing & Quality",24],["Commercial (Sales / AM)",20],["Customer Support",14],["Technology",12],["Finance & Admin",10],["Marketing",6]];
const OPS_SAL_LOC=[["Distribution Center",18914],["Field",22706],["HQ",43020]];

function esc(s){return String(s).replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;");}
function hlPy(code){const kw=new Set(["import","as","True","False","None","print"]),objs=new Set(["transactions_df","mkt_df","ops_df","booked","plt"]),mods=new Set(["pd"]);const re=/(\s+)|("(?:[^"\\]|\\.)*"|'(?:[^'\\]|\\.)*')|(\d+\.?\d*)|([A-Za-z_][A-Za-z0-9_]*)|([().,\[\]=<>!+\-*/:%&|])/g;let out="",m,prev="";while((m=re.exec(code))!==null){if(m[1]){out+=m[1];continue;}let tok=m[0],cls="t-punct";if(m[2])cls="t-str";else if(m[3])cls="t-num";else if(m[4]){if(prev===".")cls="t-method";else if(kw.has(tok))cls="t-kw";else if(objs.has(tok))cls="t-df";else if(mods.has(tok))cls="t-mod";else cls="t-ident";}out+='<span class="'+cls+'">'+esc(tok)+'</span>';prev=tok;}return out;}
function hlSql(code){const cmds=new Set(["SELECT","FROM","WHERE","GROUP","BY","ORDER","SUM","COUNT","AVG","AS","DESC","LIMIT","DISTINCT","AND"]),tables=new Set(["transactions","mkt","ops","freshket"]);const re=/(\s+)|('(?:[^'\\]|\\.)*'|"(?:[^"\\]|\\.)*")|(\d+\.?\d*)|([A-Za-z_][A-Za-z0-9_]*)|([().,*=<>!+\-\/;])/g;let out="",m;while((m=re.exec(code))!==null){if(m[1]){out+=m[1];continue;}let tok=m[0],cls="t-punct";if(m[2])cls="t-str";else if(m[3])cls="t-num";else if(m[4]){if(cmds.has(tok.toUpperCase()))cls="t-kw";else if(tables.has(tok))cls="t-table";else cls="t-ident";}out+='<span class="'+cls+'">'+esc(tok)+'</span>';}return out;}
function disp(c,v){return c==="is_chain"?(v?"True":"False"):String(v);}
function tbl(cols,rows){let h='<div class="tw"><table><thead><tr><th class="ix"></th>'+cols.map(c=>'<th>'+c+'</th>').join("")+'</tr></thead><tbody>';rows.forEach(r=>{h+='<tr><td class="ix">'+r._i+'</td>'+cols.map(c=>'<td>'+disp(c,r[c])+'</td>').join("")+'</tr>';});return h+'</tbody></table></div>';}
function ser(p,n,d){let h='<div class="ser">';p.forEach(x=>{h+='<div class="sr"><span class="sk">'+x[0]+'</span><span>'+(typeof x[1]==="number"?x[1].toLocaleString("en-US"):x[1])+'</span></div>';});return h+'<div class="sft">Name: '+n+', dtype: '+d+'</div></div>';}
function valb(t){return '<pre class="oval">'+esc(t)+'</pre>';}
function note(t){return '<div class="note">'+t+'</div>';}
function chart(el,cfg){const cv=document.createElement("canvas");cv.style.maxHeight="250px";el.appendChild(cv);new Chart(cv,cfg);}
const G=["#43d68b","#2aa56a","#5fcdb6","#5bb8ec","#b69cf0","#e88ac4","#7fd99b"];
function bo(x){return Object.assign({responsive:true,plugins:{legend:{labels:{color:"#9fc1b2"}}},scales:{x:{ticks:{color:"#9fc1b2"},grid:{color:"rgba(130,205,170,.12)"}},y:{ticks:{color:"#9fc1b2"},grid:{color:"rgba(130,205,170,.12)"}}}},x||{});}
function vc(c){const m=new Map();TDATA.forEach(r=>m.set(r[c],(m.get(r[c])||0)+1));return [...m.entries()].sort((a,b)=>b[1]-a[1]);}
function gm(c,k){const m=new Map();TDATA.forEach(r=>m.set(r[c],(m.get(r[c])||0)+r[k]));return m;}
function gmean(c,k){const s=new Map(),n=new Map();TDATA.forEach(r=>{s.set(r[c],(s.get(r[c])||0)+r[k]);n.set(r[c],(n.get(r[c])||0)+1);});const m=new Map();[...s.keys()].forEach(x=>m.set(x,Math.round(s.get(x)/n.get(x))));return m;}
function al(m){return [...m.entries()].sort((a,b)=>String(a[0]).localeCompare(String(b[0])));}
function de(m){return [...m.entries()].sort((a,b)=>b[1]-a[1]);}
function net(r){return r.gross_revenue_thb-r.discount_thb;}
function corr(x,y){const n=x.length,mx=x.reduce((a,b)=>a+b,0)/n,my=y.reduce((a,b)=>a+b,0)/n;let c=0,sx=0,sy=0;for(let i=0;i<n;i++){const dx=x[i]-mx,dy=y[i]-my;c+=dx*dy;sx+=dx*dx;sy+=dy*dy;}return c/Math.sqrt(sx*sy);}

const Q=[
// ===== EASY (12) — transactions_df =====
{t:"easy",title:"Load the dataset into pandas",ctx:`Everything starts here. Your Freshket order data sits in a file on your computer; this step reads it into pandas so you can actually work with it. We call it <code>transactions_df</code> — a clear name beats a vague <code>df</code>, because anyone reading the code instantly knows it holds the transactions.`,task:`Import pandas and read <code>freshketdanny.csv</code> into a DataFrame called <code>transactions_df</code>.`,hint:`pandas is usually shortened to <code>pd</code> when you import it. There is a read function for CSV files that just takes the file name in quotes — save what it gives you into <code>transactions_df</code>.`,a:"read_csv",py:'import pandas as pd\ntransactions_df = pd.read_csv("freshketdanny.csv")',ins:`<code>transactions_df</code> now holds every order line.`,o:e=>{e.innerHTML='<div class="okl"><i class="ti ti-check"></i> loaded — 8 rows, 10 columns (a hand-checkable slice; same code runs on the full 978-row file)</div>'+tbl(T_COLS,TDATA);}},
{t:"easy",title:"How big is this dataset?",ctx:`Before you dig in, it helps to know how big the table is — how many rows you have and how many columns (the things you know about each row).`,task:`Find the number of rows and columns in <code>transactions_df</code>.`,hint:`Every table remembers its own size. Ask <code>transactions_df</code> for its shape — no brackets after it, because it is a property, not an action.`,a:"shape",py:'transactions_df.shape',sql:'SELECT COUNT(*) AS rows FROM transactions;',ins:`8 rows by 10 columns in this slice.`,o:e=>{e.innerHTML=valb('(8, 10)');}},
{t:"easy",title:"Take a first look at the rows",ctx:`You almost never print the whole table. You glance at the first few rows to see what the columns are and what the values look like — the same quick look you would take opening a spreadsheet.`,task:`Show the first few rows of <code>transactions_df</code>.`,hint:`There is a method that shows you the top of the table; on its own it gives you the first five rows.`,a:"head",py:'transactions_df.head()',sql:'SELECT * FROM transactions LIMIT 5;',ins:`Each row is one product within a single order.`,o:e=>{e.innerHTML=tbl(T_COLS,TDATA.slice(0,5));}},
{t:"easy",title:"What type is each column?",ctx:`When pandas reads your file it decides what kind of value each column holds — words, whole numbers, or true/false. That matters, because you can add up numbers but not words. Worth a quick check before you trust the data.`,task:`Inspect the data type of every column in <code>transactions_df</code>.`,hint:`Ask <code>transactions_df</code> for its data types — like shape, it is a property, so no brackets.`,a:"dtypes",py:'transactions_df.dtypes',ins:`is_chain is a real boolean and the money columns are integers.`,o:e=>{e.innerHTML=valb('order_id            object\ncustomer_type       object\nis_chain              bool\nprovince            object\nquantity             int64\ngross_revenue_thb    int64\ndtype: object');}},
{t:"easy",title:"Pull out a single column",ctx:`Often you do not need the whole table — just one column, like revenue, to total or chart. In pandas a single column is called a <b>Series</b>.`,task:`Select just the <code>gross_revenue_thb</code> column from <code>transactions_df</code>.`,hint:`Use square brackets with the column name in quotes to pull out just that one column.`,a:'["gross_revenue_thb"]',py:'transactions_df["gross_revenue_thb"]',ins:`A Series keeps the row index beside the values.`,o:e=>{e.innerHTML=ser(TDATA.map(r=>[r._i,r.gross_revenue_thb]),"gross_revenue_thb","int64");}},
{t:"easy",title:"Count the customer types",ctx:`Freshket sells to all kinds of places — restaurants, hotels, cafés and more. A quick way to see your customer mix is to count how many orders come from each type.`,task:`Count how many orders belong to each <code>customer_type</code>.`,hint:`Take the <code>customer_type</code> column, then ask it to count how many times each value shows up.`,a:"value_counts",py:'transactions_df["customer_type"].value_counts()',sql:'SELECT customer_type, COUNT(*) AS n\nFROM transactions GROUP BY customer_type ORDER BY n DESC;',ins:`Casual Dining leads the mix.`,o:e=>{e.innerHTML=ser(vc("customer_type"),"count","int64");}},
{t:"easy",title:"How many provinces are in play?",ctx:`Freshket is growing beyond Bangkok. A fast way to sense how far it reaches is to count how many different provinces appear in the data.`,task:`Count the number of unique provinces in <code>transactions_df</code>.`,hint:`Take the <code>province</code> column, then ask for the number of different values in it.`,a:"nunique",py:'transactions_df["province"].nunique()',sql:'SELECT COUNT(DISTINCT province) FROM transactions;',ins:`Four in this slice; the full file spans nineteen.`,o:e=>{e.innerHTML=valb('4');}},
{t:"easy",title:"Add up total revenue",ctx:`The most basic business question there is: how much did we sell in total? You simply add up the revenue column. This total is the starting point for GMV, the headline number every review opens with.`,task:`Calculate the total gross revenue across all order lines.`,hint:`Take the revenue column and add it all up.`,a:"sum",py:'transactions_df["gross_revenue_thb"].sum()',sql:'SELECT SUM(gross_revenue_thb) FROM transactions;',ins:`THB 51,600 in this slice.`,o:e=>{e.innerHTML=valb('51600');}},
{t:"easy",title:"What is a typical order line size?",ctx:`An average squeezes a whole column down to one number you can compare. Here you will find the average amount of product on a line — useful for thinking about packing and delivery.`,task:`Find the average quantity per line in <code>transactions_df</code>.`,hint:`Take the <code>quantity</code> column and ask for its average.`,a:"mean",py:'transactions_df["quantity"].mean()',ins:`About 19 units — bulk B2B ordering.`,o:e=>{e.innerHTML=valb('19.125');}},
{t:"easy",title:"Summarize the numbers at a glance",ctx:`Instead of working out the count, average, smallest and largest one at a time, pandas can hand you a full summary of every number column at once — the quickest way to see the range of your figures.`,task:`Produce summary statistics for the numeric columns of <code>transactions_df</code>.`,hint:`There is a single method that gives you that whole summary in one go.`,a:"describe",py:'transactions_df.describe()',ins:`Revenue runs from THB 1,900 to 12,800 a line.`,o:e=>{const c=["quantity","gross_revenue_thb","discount_thb"];const mean=a=>Math.round(a.reduce((x,y)=>x+y,0)/a.length*100)/100;const f=(lab,fn)=>'<tr><td class="ix">'+lab+'</td>'+c.map(x=>'<td>'+fn(TDATA.map(r=>r[x]))+'</td>').join("")+'</tr>';e.innerHTML='<div class="tw"><table><thead><tr><th class="ix"></th>'+c.map(x=>'<th>'+x+'</th>').join("")+'</tr></thead><tbody>'+f("count",a=>8)+f("mean",mean)+f("min",a=>Math.min(...a))+f("max",a=>Math.max(...a))+'</tbody></table></div>';}},
{t:"easy",title:"List the available columns",ctx:`When you are about to write some analysis, you need the exact column names to type — guessing leads to typos and errors. So list them out first.`,task:`Get the list of column names in <code>transactions_df</code>.`,hint:`Ask <code>transactions_df</code> for its columns, and turn them into a plain list so they are easy to read.`,a:"columns",py:'transactions_df.columns.tolist()',ins:`Now you know every field to group, filter and chart by.`,o:e=>{e.innerHTML=valb("['order_id', 'customer_type', 'is_chain', 'province',\n 'product_category', 'channel', 'day_of_week', 'quantity',\n 'gross_revenue_thb', 'discount_thb']");}},
{t:"easy",title:"Save your work back to a file",ctx:`Your work only helps people if you can pass it on. After cleaning or adding to a table, you save it back to a file so a teammate — or a tool like MotherDuck — can pick it up. One catch: pandas adds its own row numbers unless you tell it not to.`,task:`Write <code>transactions_df</code> back to a CSV without the extra index column.`,hint:`There is a save-to-CSV method that mirrors the read one; it has a setting that turns off writing those row numbers.`,a:"to_csv",py:'transactions_df.to_csv("freshketdanny.csv", index=False)',ins:`index=False keeps the file clean — no stray unnamed first column.`,o:e=>{e.innerHTML=note('File written. With <code>index=False</code> the columns are exactly the ten you started with.');}},
// ===== INTERMEDIATE (14) =====
{t:"intermediate",title:"Show only one province",ctx:`Most of the time you do not want the whole table — you want one slice of it, like just the Phuket orders. In pandas you give it a simple rule ("the province is Phuket") and it hands back only the rows that match.`,task:`Show only the orders from Phuket in <code>transactions_df</code>.`,hint:`Put your rule inside the square brackets — <code>transactions_df[ transactions_df["province"] == "Phuket" ]</code>. The <code>==</code> means "is equal to", and pandas keeps every row where that is true.`,a:'province"]=="Phuket"',py:'transactions_df[transactions_df["province"] == "Phuket"]',sql:"SELECT * FROM transactions WHERE province = 'Phuket';",ins:`Two Phuket lines — both seafood, both high value.`,o:e=>{e.innerHTML=tbl(T_COLS,TDATA.filter(r=>r.province==="Phuket"));}},
{t:"intermediate",title:"Filter on a boolean column",ctx:`Chains order differently from independents, so you will often want to look at just one group. The <code>is_chain</code> column is already true/false, which makes this easy.`,task:`Show only chain customers in <code>transactions_df</code>.`,hint:`Use <code>is_chain</code> straight as your rule inside the brackets — it is already true or false, so there is nothing to compare.`,a:'is_chain"]==True',py:'transactions_df[transactions_df["is_chain"] == True]',sql:"SELECT * FROM transactions WHERE is_chain = TRUE;",ins:`Four of eight lines are chains here.`,o:e=>{e.innerHTML=tbl(T_COLS,TDATA.filter(r=>r.is_chain));}},
{t:"intermediate",title:"Create a calculated column",ctx:`Net revenue is just gross minus the discount. You work it out once, store it as a new column, and reuse it everywhere after.`,task:`Add a <code>net_revenue_thb</code> column to <code>transactions_df</code> equal to gross minus discount.`,hint:`Make a new column by naming it in brackets and setting it equal to the gross column minus the discount column.`,a:"net_revenue_thb",py:'transactions_df["net_revenue_thb"] = transactions_df["gross_revenue_thb"] - transactions_df["discount_thb"]\ntransactions_df[["order_id", "gross_revenue_thb", "discount_thb", "net_revenue_thb"]]',ins:`pandas runs the math down the whole column at once — no loop needed.`,o:e=>{const rows=TDATA.map(r=>({_i:r._i,order_id:r.order_id,gross_revenue_thb:r.gross_revenue_thb,discount_thb:r.discount_thb,net_revenue_thb:net(r)}));e.innerHTML=tbl(["order_id","gross_revenue_thb","discount_thb","net_revenue_thb"],rows);}},
{t:"intermediate",title:"Revenue by province, ranked",ctx:`To compare markets, you bundle all the lines for each province together, add up their revenue, then sort so the biggest market sits on top.`,task:`Total the net revenue for each province and order it highest first.`,hint:`Group the rows by province, add up the net revenue in each group, then sort the result — the ascending setting flips it so the largest is first.`,a:"groupby",py:'transactions_df.groupby("province")["net_revenue_thb"].sum().sort_values(ascending=False)',sql:"SELECT province, SUM(gross_revenue_thb - discount_thb) AS net\nFROM transactions GROUP BY province ORDER BY net DESC;",ins:`Phuket tops this slice; in the full file Bangkok leads, then the South.`,o:e=>{const m=new Map();TDATA.forEach(r=>m.set(r.province,(m.get(r.province)||0)+net(r)));e.innerHTML=ser(de(m),"net_revenue_thb","int64");}},
{t:"intermediate",title:"Lines per province",ctx:`Counting how often each value appears works on any column, not just customer types — here, how many lines came from each province.`,task:`Count how many order lines come from each province.`,hint:`Take the <code>province</code> column and count how many times each one shows up.`,a:"value_counts",py:'transactions_df["province"].value_counts()',ins:`Bangkok has the most lines here.`,o:e=>{e.innerHTML=ser(vc("province"),"count","int64");}},
{t:"intermediate",title:"Top categories by revenue",ctx:`Ranking and keeping the top few answers the everyday question: "what are our biggest sellers?"`,task:`Find the top 3 product categories by gross revenue.`,hint:`Group by product category, add up the revenue, sort from high to low, then keep the first three.`,a:"head(3)",py:'transactions_df.groupby("product_category")["gross_revenue_thb"].sum().sort_values(ascending=False).head(3)',ins:`Seafood dominates — high price per kilo.`,o:e=>{e.innerHTML=ser(de(gm("product_category","gross_revenue_thb")).slice(0,3),"gross_revenue_thb","int64");}},
{t:"intermediate",title:"Bar chart: revenue by province",ctx:`A column of totals is far easier to read as a bar chart. pandas can draw one straight from your grouped numbers using matplotlib, the standard charting library.`,task:`Draw a bar chart of gross revenue by province.`,hint:`First group and total the revenue, then ask it to plot as a bar chart; bring in matplotlib and show the figure.`,a:"plot",py:'import matplotlib.pyplot as plt\ntransactions_df.groupby("province")["gross_revenue_thb"].sum().plot(kind="bar")\nplt.show()',ins:`The bars make Phuket's lead obvious at a glance.`,o:e=>{const a=al(gm("province","gross_revenue_thb"));chart(e,{type:"bar",data:{labels:a.map(x=>x[0]),datasets:[{label:"gross revenue (THB)",data:a.map(x=>x[1]),backgroundColor:G[0]}]},options:bo()});}},
{t:"intermediate",title:"Bar chart: orders by customer type",ctx:`Counts turn into bars naturally — the taller the bar, the more orders.`,task:`Draw a bar chart of the number of orders per customer_type.`,hint:`Count the orders per customer type, then plot that as a bar chart.`,a:"plot",py:'transactions_df["customer_type"].value_counts().plot(kind="bar")\nplt.show()',ins:`Casual Dining is the tallest bar — your core segment.`,o:e=>{const v=vc("customer_type");chart(e,{type:"bar",data:{labels:v.map(x=>x[0]),datasets:[{label:"orders",data:v.map(x=>x[1]),backgroundColor:G[2]}]},options:bo()});}},
{t:"intermediate",title:"Line chart: revenue across the week",ctx:`When time runs along the bottom, a line chart fits best. You add up revenue per day, put the days in Monday-to-Sunday order, then draw the line.`,task:`Plot gross revenue across the days of the week as a line.`,hint:`Group by day and total the revenue, reorder the days so they run Monday to Sunday, then plot it as a line.`,a:"plot",py:'order = ["Monday","Tuesday","Wednesday","Thursday","Friday","Saturday","Sunday"]\ntransactions_df.groupby("day_of_week")["gross_revenue_thb"].sum().reindex(order).plot(kind="line", marker="o")\nplt.show()',ins:`Friday peaks — restaurants stock up before the weekend.`,o:e=>{const WEEK=["Monday","Tuesday","Wednesday","Thursday","Friday","Saturday","Sunday"];const m=gm("day_of_week","gross_revenue_thb");chart(e,{type:"line",data:{labels:WEEK,datasets:[{label:"gross revenue (THB)",data:WEEK.map(d=>m.get(d)||0),borderColor:G[0],backgroundColor:G[0],tension:.25,pointRadius:4}]},options:bo()});}},
{t:"intermediate",title:"Filter on two conditions",ctx:`Real questions usually mix conditions — here, customers that are chains and in Bangkok at the same time.`,task:`Show chain customers located in Bangkok.`,hint:`Join two rules with <code>&</code> (which means "and"), and wrap each rule in its own parentheses, or pandas reads it wrong.`,a:"&",py:'transactions_df[(transactions_df["is_chain"] == True) & (transactions_df["province"] == "Bangkok")]',sql:"SELECT * FROM transactions WHERE is_chain = TRUE AND province = 'Bangkok';",ins:`& means AND; the parentheses are required or pandas misreads the order of operations.`,o:e=>{e.innerHTML=tbl(T_COLS,TDATA.filter(r=>r.is_chain&&r.province==="Bangkok"));}},
{t:"intermediate",title:"Marketing spend by channel (mkt_df)",ctx:`Now switch tables. <code>mkt_df</code> is your marketing data, and it lives in its own file — <code>freshket_mkt.csv</code> — so the first thing you do is read it in, exactly the way you read the transactions. One row is one channel in one week.`,task:`Load <code>freshket_mkt.csv</code> into <code>mkt_df</code>, then total the spend for each channel, highest first.`,hint:`Read the new file with <code>pd.read_csv</code> first, then group <code>mkt_df</code> by channel, add up <code>spend_thb</code>, and sort from high to low.`,a:"groupby",py:'mkt_df = pd.read_csv("freshket_mkt.csv")\nmkt_df.groupby("channel")["spend_thb"].sum().sort_values(ascending=False)',sql:"SELECT channel, SUM(spend_thb) AS spend\nFROM mkt GROUP BY channel ORDER BY spend DESC;",ins:`Facebook and Google absorb most of the budget — the paid-social workhorses.`,o:e=>{e.innerHTML=ser(MKT_SPEND,"spend_thb","int64")+note('<div class="sub2">from the full mkt_df (70 rows, 10 weeks).</div>');}},
{t:"intermediate",title:"Cheapest channel to acquire a customer (mkt_df)",ctx:`Spending a lot is not the same as spending well. CAC — what it costs to win one customer — tells you which channel pulls its weight per baht.`,task:`Using <code>mkt_df</code>, show the average CAC per channel, cheapest first.`,hint:`Group <code>mkt_df</code> by channel, take the average CAC, and sort so the cheapest channel comes first.`,a:"groupby",py:'mkt_df.groupby("channel")["cac_thb"].mean().sort_values()',ins:`Referral (฿806) and Email (฿1,337) are far cheaper than paid social — owned channels win on efficiency.`,o:e=>{e.innerHTML=ser(MKT_CAC,"cac_thb","int64")+note('<div class="sub2">from the full mkt_df.</div>');}},
{t:"intermediate",title:"Headcount by department (ops_df)",ctx:`Third table, third file. <code>ops_df</code> is your people, and it comes from <code>freshket_ops.csv</code> — so you read it in first, just like the others. One row is one employee.`,task:`Load <code>freshket_ops.csv</code> into <code>ops_df</code>, then count how many employees are in each department.`,hint:`Read the file with <code>pd.read_csv</code> first, then take the <code>department</code> column and count how many times each value appears.`,a:"value_counts",py:'ops_df = pd.read_csv("freshket_ops.csv")\nops_df["department"].value_counts()',sql:"SELECT department, COUNT(*) AS n\nFROM ops GROUP BY department ORDER BY n DESC;",ins:`Warehouse, logistics and sourcing are ~69% of staff — the signature of a vertically-integrated food distributor.`,o:e=>{e.innerHTML=ser(OPS_DEPT,"count","int64")+note('<div class="sub2">from the full ops_df (201 employees).</div>');}},
{t:"intermediate",title:"Average salary by location (ops_df)",ctx:`Grouping and averaging turns the salary column into a clean comparison across the company's three kinds of location.`,task:`Using <code>ops_df</code>, find the average monthly salary for each <code>location_type</code>.`,hint:`Group <code>ops_df</code> by <code>location_type</code> and take the average of the monthly salary.`,a:"groupby",py:'ops_df.groupby("location_type")["monthly_salary_thb"].mean()',ins:`HQ pays ~฿43k vs ~฿19k at the distribution centre — the skills mix, not unfairness, drives the gap.`,o:e=>{e.innerHTML=ser(OPS_SAL_LOC,"monthly_salary_thb","float64")+note('<div class="sub2">from the full ops_df.</div>');}},
// ===== HARD (6) =====
{t:"hard",title:"Pivot table: province × chain",ctx:`A pivot table lays two things out as a grid — here, revenue with provinces down the side and chain-or-not across the top — so you can read both at once.`,task:`Build a pivot table of gross revenue with province as rows and is_chain as columns.`,hint:`Use pandas' pivot table: tell it the values to add up, what goes down the rows, what goes across the columns, and to fill any blanks with zero.`,a:"pivot_table",py:'pd.pivot_table(transactions_df, values="gross_revenue_thb",\n               index="province", columns="is_chain",\n               aggfunc="sum", fill_value=0)',ins:`Reading across a row shows how much of each province is chain vs independent.`,o:e=>{const pr=[...new Set(TDATA.map(r=>r.province))].sort();let h='<div class="tw"><table><thead><tr><th class="ix">province</th><th>False</th><th>True</th></tr></thead><tbody>';pr.forEach(p=>{const F=TDATA.filter(r=>r.province===p&&!r.is_chain).reduce((a,r)=>a+r.gross_revenue_thb,0),T=TDATA.filter(r=>r.province===p&&r.is_chain).reduce((a,r)=>a+r.gross_revenue_thb,0);h+='<tr><td class="ix">'+p+'</td><td>'+F+'</td><td>'+T+'</td></tr>';});e.innerHTML=h+'</tbody></table></div>';}},
{t:"hard",title:"Average order value",ctx:`Average order value is per order, but your data is per line — so first you add the lines up into whole orders, then average those. That two-step is the key habit whenever an order can have several lines.`,task:`Compute the average revenue per order (not per line).`,hint:`Group by <code>order_id</code> and add up to get one total per order, then take the average of those totals.`,a:"groupby",py:'transactions_df.groupby("order_id")["gross_revenue_thb"].sum().mean()',sql:"SELECT AVG(t) FROM (SELECT order_id, SUM(gross_revenue_thb) t\n  FROM transactions GROUP BY order_id);",ins:`Here each order has one line so it equals the row mean; on the full file this first collapses many lines per order.`,o:e=>{e.innerHTML=valb('6450.0');}},
{t:"hard",title:"Stacked bar: chain vs independent",ctx:`A stacked bar shows the total and how it splits, in one bar. You build the province-by-chain grid, then plot it stacked.`,task:`Plot a stacked bar of revenue by province, split into chain vs independent.`,hint:`Make the same province-by-chain grid as the pivot question, then plot it as a bar chart with stacking turned on.`,a:"stacked",py:'transactions_df.pivot_table(values="gross_revenue_thb", index="province",\n               columns="is_chain", aggfunc="sum", fill_value=0) \\\n  .plot(kind="bar", stacked=True)\nplt.show()',ins:`Each bar is total revenue; the colours show how dependent a province is on chains.`,o:e=>{const pr=[...new Set(TDATA.map(r=>r.province))].sort();const ind=pr.map(p=>TDATA.filter(r=>r.province===p&&!r.is_chain).reduce((a,r)=>a+r.gross_revenue_thb,0)),ch=pr.map(p=>TDATA.filter(r=>r.province===p&&r.is_chain).reduce((a,r)=>a+r.gross_revenue_thb,0));chart(e,{type:"bar",data:{labels:pr,datasets:[{label:"independent",data:ind,backgroundColor:G[2]},{label:"chain",data:ch,backgroundColor:G[0]}]},options:bo({scales:{x:{stacked:true,ticks:{color:"#9fc1b2"},grid:{color:"rgba(130,205,170,.12)"}},y:{stacked:true,ticks:{color:"#9fc1b2"},grid:{color:"rgba(130,205,170,.12)"}}}})});}},
{t:"hard",title:"Correlation and a scatter plot",ctx:`Do bigger orders bring in more money? A correlation gives you one number for how strongly two things move together, and a scatter plot shows the shape of it.`,task:`Compute the correlation between quantity and gross revenue, then draw a scatter plot of the two.`,hint:`Ask one column for its correlation with the other; then draw a scatter plot with quantity along the bottom and revenue up the side.`,a:"corr",py:'print(transactions_df["quantity"].corr(transactions_df["gross_revenue_thb"]))\ntransactions_df.plot(kind="scatter", x="quantity", y="gross_revenue_thb")\nplt.show()',ins:`Positive but loose — price per unit varies by category, so quantity alone does not set revenue.`,o:e=>{const c=Math.round(corr(TDATA.map(r=>r.quantity),TDATA.map(r=>r.gross_revenue_thb))*1000)/1000;const d=document.createElement("div");d.innerHTML=valb("correlation = "+c);e.appendChild(d);chart(e,{type:"scatter",data:{datasets:[{label:"orders",data:TDATA.map(r=>({x:r.quantity,y:r.gross_revenue_thb})),backgroundColor:G[0],pointRadius:6}]},options:bo({scales:{x:{title:{display:true,text:"quantity",color:"#9fc1b2"},ticks:{color:"#9fc1b2"},grid:{color:"rgba(130,205,170,.12)"}},y:{title:{display:true,text:"gross_revenue_thb",color:"#9fc1b2"},ticks:{color:"#9fc1b2"},grid:{color:"rgba(130,205,170,.12)"}}}})});}},
{t:"hard",title:"Is marketing paying off? (mkt_df vs transactions_df)",ctx:`This links two tables by idea, not by matching rows: compare what it costs to win a customer (from <code>mkt_df</code>) against what an order is worth (from <code>transactions_df</code>).`,task:`From <code>mkt_df</code>, compute blended CAC = total spend ÷ total new customers, and compare it to the AOV you found earlier.`,hint:`Add up all the spend and all the new customers in <code>mkt_df</code> and divide one by the other; then set that beside the roughly THB 12,548 average order value from transactions.`,a:"sum",py:'blended_cac = mkt_df["spend_thb"].sum() / mkt_df["new_customers"].sum()\nblended_cac',ins:`Blended CAC ≈ ฿2,879 against an AOV of ฿12,548 — a new customer's very first order more than pays back acquisition. That is a healthy growth engine.`,o:e=>{e.innerHTML=valb('2879.0')+note('<div class="sub2">total spend ฿973,114 ÷ 338 new customers = ฿2,879. AOV (transactions_df) = ฿12,548.</div>');}},
{t:"hard",title:"Is acquisition accelerating? (mkt_df)",ctx:`Rolling <code>mkt_df</code> up to the week shows the trend a growth team cares about: are we winning more customers as time goes on?`,task:`From <code>mkt_df</code>, total new customers per week and plot the trend.`,hint:`Group <code>mkt_df</code> by week, add up the new customers, and plot it as a line — the weeks are already in order.`,a:"groupby",py:'mkt_df.groupby("week")["new_customers"].sum().plot(kind="line", marker="o")\nplt.show()',ins:`25 → 47 new customers a week over ten weeks — acquisition is accelerating, in step with the expansion push.`,o:e=>{chart(e,{type:"line",data:{labels:MKT_WEEKLY.map(x=>x[0].slice(5)),datasets:[{label:"new customers / week",data:MKT_WEEKLY.map(x=>x[1]),borderColor:G[0],backgroundColor:G[0],tension:.25,pointRadius:4}]},options:bo()});}}
];
const SUB={easy:"12 questions — read &amp; summarize transactions_df.",intermediate:"14 questions — filter, group &amp; plot, and meet mkt_df &amp; ops_df.",hard:"6 questions — pivots, AOV, charts, and connecting the three dataframes."};
const LBL={py:"python",sql:"sql (same question)"};
function cb(label,lang,code){return '<div class="lng">'+label+'</div><pre class="code">'+(lang==="py"?hlPy(code):hlSql(code))+'</pre>';}
var seen=new Set();
function up(){var tot=Q.length;document.getElementById("pc").textContent=seen.size+" / "+tot;document.getElementById("bar").style.width=(seen.size/tot*100)+"%";}
function build(t){var w=document.getElementById("qw");w.innerHTML="";document.getElementById("tsub").innerHTML=SUB[t]||"";Array.prototype.forEach.call(document.querySelectorAll(".tab"),function(x){x.classList.toggle("on",x.dataset.t===t);});
 var n=0;Q.forEach(function(q,gi){if(q.t!==t)return;n++;var c=document.createElement("div");c.className="qc";
  c.innerHTML='<div class="qh"><span class="st">'+n+'</span><span class="qt">'+q.title+'</span></div><div class="ctx">'+q.ctx+'</div><div class="task"><b>Your task:</b> '+q.task+'</div><div class="lab">your answer</div><textarea placeholder="type the code, or just take the hint and reveal"></textarea><div class="btns"><button class="b hb"><i class="ti ti-bulb"></i> Show hint</button><button class="b ck"><i class="ti ti-check"></i> Check</button><button class="b rev"><i class="ti ti-eye"></i> Reveal solution</button><span class="fb"></span></div><div class="hintbox"><i class="ti ti-bulb"></i> Hint: '+q.hint+'</div><div class="sol"></div>';
  var ta=c.querySelector("textarea"),fb=c.querySelector(".fb"),hb=c.querySelector(".hintbox"),sol=c.querySelector(".sol");
  c.querySelector(".hb").addEventListener("click",function(){hb.style.display=hb.style.display==="block"?"none":"block";});
  c.querySelector(".ck").addEventListener("click",function(){var nm=function(s){return s.toLowerCase().replace(/\s+/g,"").replace(/'/g,'"');};var u=nm(ta.value);if(!u){fb.textContent="type an attempt first";fb.className="fb";return;}if(u.indexOf(nm(q.a))>=0){fb.textContent="✓ looks right";fb.className="fb g";}else{fb.textContent="not quite — take the hint, then reveal";fb.className="fb b";}});
  c.querySelector(".rev").addEventListener("click",function(){if(!sol.dataset.d){var h=cb(LBL.py,"py",q.py);if(q.sql)h+=cb(LBL.sql,"sql",q.sql);h+='<div class="ol">output</div>';sol.innerHTML=h;var ob=document.createElement("div");ob.className="ob";sol.appendChild(ob);q.o(ob);var ins=document.createElement("div");ins.className="ins";ins.innerHTML='<b>Insight:</b> '+q.ins;sol.appendChild(ins);sol.dataset.d="1";sol.style.display="block";seen.add(gi);up();}else{sol.style.display=sol.style.display==="none"?"block":"none";}});
  w.appendChild(c);});}
Array.prototype.forEach.call(document.querySelectorAll(".tab"),function(x){x.addEventListener("click",function(){build(x.dataset.t);});});
build("easy");up();
